# Generated by Django 4.0.5 on 2022-06-03 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=13)),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=512)),
                ('is_loaned', models.BooleanField(default=False)),
            ],
        ),
    ]
