# Generated by Django 4.0.5 on 2022-06-05 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_book_author_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='book_category',
            field=models.ManyToManyField(to='books.book'),
        ),
    ]
